# Generated by Django 6.0.3 on 2026-04-01 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Traiteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomcomplet', models.CharField(max_length=100, verbose_name='Nom complet')),
                ('specialite', models.TextField(verbose_name='Specialité')),
                ('description', models.TextField(verbose_name='Description')),
                ('adresse', models.CharField(max_length=100, verbose_name='Adresse')),
                ('est_actif', models.BooleanField(default=True, verbose_name='Etat')),
                ('email', models.EmailField(max_length=255, verbose_name='Email')),
                ('date_creation', models.DateField(auto_now_add=True, verbose_name='Date de création')),
                ('telephone', models.CharField(max_length=11, verbose_name='Téléphone')),
                ('image', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
