# Generated by Django 6.0.3 on 2026-04-02 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traiteur',
            name='image',
            field=models.URLField(blank=True, max_length=300, verbose_name='Image'),
        ),
    ]
